# Generated by Django 4.2.3 on 2023-07-13 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_book_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Janre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('janre_book', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='janre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='first.janre'),
        ),
    ]
