# Generated by Django 4.2.3 on 2023-07-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_janre_book_janre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ff',
            field=models.CharField(default=0, max_length=400),
            preserve_default=False,
        ),
    ]
