# Generated by Django 4.2.3 on 2023-07-18 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_book_ff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='ff',
        ),
    ]
