# Generated by Django 4.2.3 on 2023-07-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0007_book_author_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
