# Generated by Django 4.2.3 on 2023-10-31 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0008_alter_book_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='USD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_now', models.FloatField()),
                ('data', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
